version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-flavormetrics
    env_file:
      - .env
    volumes:
      - postgres_data_:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data_: