services:
  db:
    image: postgres:17-alpine
    container_name: postgres_flavormetrics
    environment:
      POSTGRES_USER: narcis
      POSTGRES_PASSWORD: coffee1234
      POSTGRES_DB: flavormetrics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: flavormetrics_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/flavormetrics
      SPRING_DATASOURCE_USERNAME: narcis
      SPRING_DATASOURCE_PASSWORD: coffee1234
    depends_on:
      - db

volumes:
  postgres_data: